const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-silm-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt ',
    },
    {
      name: 'Adidas Slim shirt',
      slug: 'adidas-silm-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product ',
    },
    {
      name: 'Nike Slim pant',
      slug: 'nike-silm-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product ',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product ',
    },
  ],
};
export default data;
